# Generated by Django 5.0.2 on 2024-02-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
    ]
