# Generated by Django 5.0.2 on 2024-02-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20240215_1620'),
    ]

    operations = [
    ]
